version: '3.8'
services:
    test:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: technical_prod
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    webserver:
        image: nginx:1.23.1-alpine
        container_name: server_technical_nginx_prod
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d
    db:
        image: mysql:5.7
        restart: always
        ports:
          - 8000:3306
        environment:
          MYSQL_DATABASE: technical_tes
          MYSQL_USER: ricardo
          MYSQL_PASSWORD: root123
          MYSQL_ROOT_PASSWORD: rootpass
        volumes:
          - ./mysql:/var/lib/mysql